version: '3.8'
services:
  server:
    image: server
    ports:
      - '4000:4000'
    build:
      context: .
    volumes:
      - .:/usr/src/app
    networks:
      - app
    depends_on:
      - mongo
  mongo:
    image: mongo:3.6.19-xenial
    ports:
      - '27017:27017'
    networks:
      - app
    volumes:
      - mongo-data:/data/db
networks:
  app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
